/* MasterSelfLearn — zero-dependency front end.
 *
 * Every page loads data/site.js (generated by msl/sitegen.py) and renders it.
 * Nothing here computes a figure: if a number is on screen it came out of the
 * ledger.  Where a value is missing the UI says "no verified value", it does not
 * substitute zero, a dash that looks like zero, or a guess.
 */
(function () {
  "use strict";

  var D = window.MSLDATA || null;

  // ---------------------------------------------------------------- helpers
  function h(tag, attrs, kids) {
    var el = document.createElement(tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        var v = attrs[k];
        if (v === null || v === undefined || v === false) return;
        if (k === "class") el.className = v;
        else if (k === "html") el.innerHTML = v;
        else if (k === "text") el.textContent = v;
        else if (k.slice(0, 2) === "on" && typeof v === "function") {
          el.addEventListener(k.slice(2), v);
        } else el.setAttribute(k, v);
      });
    }
    (kids || []).forEach(function (c) {
      if (c === null || c === undefined || c === false) return;
      el.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    });
    return el;
  }
  function n(v, digits) {
    if (v === null || v === undefined || v === "" || Number.isNaN(Number(v))) return "—";
    return Number(v).toLocaleString("en-US",
      { maximumFractionDigits: digits === undefined ? 0 : digits });
  }
  function pct(v, digits) {
    if (v === null || v === undefined) return "—";
    return (v * 100).toFixed(digits === undefined ? 1 : digits) + "%";
  }
  function signed(v, digits) {
    // NaN must never reach the page.  A renamed or missing field used to render
    // as the literal string "NaN" in the cycle-delta line; showing an em dash is
    // honest, showing NaN is a bug the reader has to work around.
    if (v === null || v === undefined || !Number.isFinite(Number(v))) return "—";
    var x = Number(v);
    return (x > 0 ? "+" : "") + x.toFixed(digits === undefined ? 2 : digits);
  }
  function ago(iso) {
    if (!iso) return "—";
    var t = Date.parse(iso);
    if (Number.isNaN(t)) return iso;
    var s = Math.max(0, (Date.now() - t) / 1000);
    if (s < 60) return Math.floor(s) + "s ago";
    if (s < 3600) return Math.floor(s / 60) + "m ago";
    if (s < 86400) return Math.floor(s / 3600) + "h ago";
    return Math.floor(s / 86400) + "d ago";
  }
  function short(s, k) {
    if (!s) return "";
    return s.length > k ? s.slice(0, k - 1) + "…" : s;
  }
  function badge(text, cls) { return h("span", { class: "badge " + (cls || ""), text: text }); }
  function link(url, label, title) {
    if (!url) return h("span", { class: "small", text: "—" });
    return h("a", { href: url, target: "_blank", rel: "noopener noreferrer", title: title || url, text: label || url });
  }
  function empty(msg) { return h("p", { class: "empty", text: msg }); }
  function table(headers, rows, opts) {
    var o = opts || {};
    var thead = h("thead", {}, [h("tr", {}, headers.map(function (x, i) {
      return h("th", { class: o.nums && o.nums.indexOf(i) >= 0 ? "num" : null, text: x });
    }))]);
    var tbody = h("tbody", {}, rows);
    return h("div", { class: "tablewrap" }, [h("table", {}, [thead, tbody])]);
  }
  function tr(cells) { return h("tr", {}, cells); }
  function td(x, cls) {
    // Accepts a value, one node, or an array of nodes.  An array used to fall
    // through to String(x) and print "[object Object]" in the cell, which is a
    // bug a reader cannot tell apart from real data.
    var kids;
    if (x && x.nodeType) kids = [x];
    else if (Array.isArray(x)) kids = x.map(function (c) {
      return c && c.nodeType ? c : document.createTextNode(String(c));
    });
    else kids = [document.createTextNode(x === null || x === undefined ? "—" : String(x))];
    return h("td", { class: cls || null }, kids);
  }
  function tdn(v, digits) { return td(n(v, digits), "num"); }
  function section(id, title, count, body) {
    var s = h("section", { id: id }, [
      h("h2", {}, [document.createTextNode(title),
      count === null || count === undefined ? null : h("span", { class: "n", text: String(count) })]),
    ]);
    (Array.isArray(body) ? body : [body]).forEach(function (b) { if (b) s.appendChild(b); });
    return s;
  }

  // ------------------------------------------------------------------ shell
  var PAGES = [
    ["index.html", "Today"],
    ["library.html", "Library"],
    ["projects.html", "Projects"],
    ["leaderboard.html", "Competition"],
    ["ideas.html", "Ideas"],
    ["evidence.html", "Evidence"],
    ["sources.html", "Sources"],
    ["irregularities.html", "Flags"],
    ["cycles.html", "Cycles"],
    ["methodology.html", "How it thinks"],
  ];

  function shell() {
    var page = document.body.getAttribute("data-page") || "index.html";
    var meta = (D && D.meta) || {};

    var pulse = D
      ? h("span", { class: "pulse", html:
          "cycle <b>" + D.autoCounts.cycle + "</b> · " + ago(meta.generatedAt) +
          " · next in <b data-next>" + meta.intervalMinutes + "m</b>" })
      : h("span", { class: "pulse", text: "no data/site.js" });

    var nav = h("nav", { class: "tabs", "aria-label": "Sections" }, PAGES.map(function (p) {
      return h("a", { href: p[0], text: p[1], "aria-current": p[0] === page ? "page" : null });
    }));

    var themeBtn = h("button", {
      class: "mini", type: "button", text: "Theme",
      onclick: function () {
        var cur = document.documentElement.getAttribute("data-theme") === "light" ? "" : "light";
        document.documentElement.setAttribute("data-theme", cur);
        try { localStorage.setItem("msl-theme", cur); } catch (e) {}
      },
    });
    try {
      var saved = localStorage.getItem("msl-theme");
      if (saved) document.documentElement.setAttribute("data-theme", saved);
    } catch (e) {}

    var head = h("header", { class: "top" }, [h("div", { class: "wrap top-row" }, [
      h("a", { class: "brand", href: "index.html" }, [
        h("span", { class: "dot" }),
        document.createTextNode("MasterSelfLearn"),
        h("small", { text: "autonomous research engine" }),
      ]),
      pulse,
      h("span", { class: "spacer" }),
      nav,
      themeBtn,
    ])]);

    document.body.insertBefore(head, document.body.firstChild);

    var foot = h("footer", { class: "bottom" }, [h("div", { class: "wrap" }, [
      h("span", { text: "Generated " + (meta.generatedAt || "—") + " by msl/sitegen.py at cycle " + (D ? D.autoCounts.cycle : "—") + "." }),
      link(meta.repoUrl, "Repository"),
      link(meta.masterSiteUrl, "MasterSite"),
      link((meta.repoUrl || "") + "/blob/main/VERIFICATION.md", "Audit ledger"),
      link((meta.repoUrl || "") + "/blob/main/IRREGULARITIES.md", "Irregularities"),
      link((meta.repoUrl || "") + "/blob/main/METHODOLOGY.md", "Methodology"),
      link((meta.repoUrl || "") + "/blob/main/ROADMAP.md", "Roadmap"),
      h("span", { class: "spacer" }),
      h("span", { text: "No manual input · no API keys · no language model in the loop." }),
    ])]);
    document.body.appendChild(foot);

    // countdown to the next cron slot
    var el = document.querySelector("[data-next]");
    if (el && meta.intervalMinutes) {
      var tick = function () {
        var mins = meta.intervalMinutes;
        var d = new Date();
        var passed = d.getUTCMinutes() % mins;
        var left = mins - passed - d.getUTCSeconds() / 60;
        if (left < 0) left += mins;
        var m = Math.floor(left), s = Math.floor((left - m) * 60);
        el.textContent = m + "m " + (s < 10 ? "0" : "") + s + "s";
      };
      tick();
      setInterval(tick, 1000);
    }
  }

  function noData(main) {
    main.appendChild(h("div", { class: "note crit", html:
      "<b>data/site.js is missing.</b> Nothing is rendered rather than rendering " +
      "placeholders, because a placeholder on this site would be a fabricated " +
      "figure. Run <code>python3 -m msl.cli cycle --offline</code> to regenerate it." }));
  }

  // ============================================================ TODAY page
  function pageToday(main) {
    var ac = D.autoCounts, rep = D.report, counts = D.irregularityCounts;
    var openCrit = D.irregularities.filter(function (i) { return i.severity === "critical" && i.status === "open"; });
    var openWarn = D.irregularities.filter(function (i) { return i.severity === "warn" && i.status === "open"; });

    main.appendChild(h("h1", { text: "Today's briefing" }));
    main.appendChild(h("p", { class: "lede", text:
      "Everything below came from classified public sources in an unattended cycle. " +
      "Official, trusted-registry, community, mirror, and undocumented first-party " +
      "sources are labelled separately. Every number links to its source. Nothing was written by " +
      "a model from memory — the reasoning stage is a fixed rule set over the " +
      "accepted ledger, which is what makes it checkable." }));

    main.appendChild(h("div", { class: "stats" }, [
      stat("Accepted claims", n(ac.claims),
           n(ac.strictTraceClaims) + " strict · " + n(ac.legacyTraceClaims) + " legacy",
           "ok"),
      stat("Topics", n(ac.topics), n(ac.newTopics) + " new · " + D.families.length + " families", ""),
      stat("Ideas", n(ac.ideas), n(ac.ideasPromoted) + " promoted", "ok"),
      stat("Personas scored", n(ac.forecastsScored), n(ac.forecastsIssued) + " forecasts issued", ""),
      stat("Sources verified", ac.sourcesVerified + " / " + ac.sourcesRegistered, ac.sourcesBlocked + " blocked", ac.sourcesBlocked ? "warn" : "ok"),
      stat("Open flags", n(counts.open), counts.critical + " critical · " + counts.warn + " warn", counts.critical ? "bad" : (counts.warn ? "warn" : "ok")),
    ]));

    // what changed
    var hist = D.cycles.slice(-2);
    var delta = null;
    if (hist.length === 2) {
      var a = hist[0], b = hist[1];
      delta = h("div", { class: "note" }, [
        h("b", { text: "Since the previous cycle (" + a.cycle + " → " + b.cycle + "): " }),
        document.createTextNode("claims " + signed(b.claimsTotal - a.claimsTotal, 0) +
          ", topics " + signed(b.topicsTotal - a.topicsTotal, 0) +
          ", ideas " + signed(b.ideas - a.ideas, 0) +
          ", forecasts scored " + signed(b.forecastsScored - a.forecastsScored, 0) +
          ", open flags " + signed(b.irregularitiesOpen - a.irregularitiesOpen, 0) +
          ", reads " + signed(b.fetchOk - a.fetchOk, 0) + "."),
      ]);
    }
    if (delta) main.appendChild(delta);

    if (!rep.ok || rep.errors.length) {
      main.appendChild(h("div", { class: "note crit" }, [
        h("b", { text: "The last cycle reported errors. " }),
        document.createTextNode(rep.errors.join(" · ")),
      ]));
    }

    // headline insights
    var ins = D.insights.slice(0, 12);
    main.appendChild(section("insights", "What the reasoning stage concluded", ins.length,
      ins.length ? h("ul", { class: "list" }, ins.map(function (i) {
        return h("li", {}, [
          h("div", { class: "t", text: i.text }),
          h("div", { class: "m" }, [
            badge(i.kind, "acc"), badge(i.topic, "mute"),
            document.createTextNode("  importance " + i.importance.toFixed(2)),
            document.createTextNode(" · derived from "),
            h("a", { href: "evidence.html#claim-" + i.claimIds[0], text: i.claimIds.join(", ") }),
          ]),
        ]);
      })) : empty("No insight yet. Insights are derived claims; they appear once the ledger holds two observations of the same field.")));

    // attention movers
    var topics = D.topics.filter(function (t) { return t.verifiedClaims > 0; }).slice(0, 10);
    main.appendChild(section("trending", "Topics with the most verified claim rows", topics.length,
      topics.length ? table(["Topic", "Family", "Signals", "Verified claims", "Interest", "Status"],
        topics.map(function (t) {
          return tr([
            td(h("a", { href: "library.html#" + encodeURIComponent(t.slug), text: t.title })),
            td(short(t.familyTitle, 26)), tdn(t.signals), tdn(t.verifiedClaims),
            td(t.interestScore.toFixed(2), "num"),
            td(badge(t.status, t.status === "active" ? "ok" : (t.status === "retired" ? "mute" : "info"))),
          ]);
        }), { nums: [2, 3, 4] })
        : empty("No topic has an accepted claim yet.")));

    // leaderboard snapshot
    var lb = D.leaderboard || {};
    var ranked = (lb.ranked || []).slice(0, 8);
    main.appendChild(section("board", "Persona competition", (lb.ranked || []).length + " ranked",
      [ranked.length ? table(["#", "Persona", "Paired", "Paired accuracy", "Skill vs paired null"],
        ranked.map(function (r, i) {
          return tr([td(i + 1), td(h("a", { href: "leaderboard.html#" + r.strategyId, text: r.name })),
            tdn(r.pairedScored), td(pct(r.pairedAccuracy)),
            td(h("span", { class: (r.skill || 0) >= 0 ? "up" : "down", text: signed((r.skill || 0) * 100, 1) + " pts" }), "num")]);
        }), { nums: [0, 2, 3, 4] })
        : h("div", { class: "note warn", html:
            "<b>No persona is ranked yet, and that is the correct state.</b> A persona needs " +
            D.leaderboard.qualification.minScoredForecasts + " paired scored forecasts " +
            "before a rank means anything. Until then every persona is reported UNRANKED " +
            "with the reason rather than shown at 0%." }),
        h("p", { class: "small", text:
          "Skill compares a persona and S10_Persistence only where both forecast the " +
          "same metric and cycle. A global null accuracy over a different target mix is not used." })]));

    // top ideas
    var ideas = (D.ideas || []).slice(0, 6);
    main.appendChild(section("ideas", "Ideas holding up best", (D.ideas || []).length,
      ideas.length ? h("ul", { class: "list" }, ideas.map(function (i) {
        return h("li", {}, [
          h("div", { class: "t" }, [h("a", { href: "ideas.html#" + i.id, text: i.title })]),
          h("div", { class: "m" }, [
            badge(i.kind, "acc"), badge(i.status, i.status === "promoted" ? "ok" : "mute"),
            document.createTextNode("  robustness " + i.robustness.toFixed(3) +
              " · " + i.lineage.length + " accepted claims · " + i.sources.length + " sources · seen " + i.appearances + "×"),
          ]),
        ]);
      })) : empty("No idea has a verified lineage yet.")));

    // flags needing a human
    var needReview = openCrit.concat(openWarn).slice(0, 8);
    main.appendChild(section("review", "Flagged for review", counts.open + " open",
      needReview.length ? h("ul", { class: "list" }, needReview.map(function (i) {
        return h("li", {}, [
          h("div", { class: "t" }, [badge(i.id, i.severity), document.createTextNode("  " + i.title)]),
          h("div", { class: "m", text: short(i.detail, 260) }),
          h("div", { class: "m" }, [
            document.createTextNode("first seen cycle " + i.firstSeenCycle + " · " + i.occurrences + " occurrence(s)"),
            i.standing ? badge("standing", "mute") : null,
            i.repro ? h("span", {}, [document.createTextNode(" · "), h("code", { text: short(i.repro, 90) })]) : null,
          ]),
        ]);
      })) : empty("No critical or warn irregularity is open.")));

    // lessons
    var lessons = (D.memory.lessons || []);
    main.appendChild(section("lessons", "What the engine has learned about itself", lessons.length,
      lessons.length ? table(["", "Lesson (counted, not reflected)"],
        lessons.map(function (l) {
          return tr([td(h("code", { text: l.id })), td(l.statement)]);
        }))
        : empty("No lesson has enough supporting counts yet.")));
  }

  function stat(k, v, s, cls) {
    return h("div", { class: "stat " + (cls || "") }, [
      h("div", { class: "k", text: k }),
      h("div", { class: "v", text: v }),
      h("div", { class: "s", text: s }),
    ]);
  }

  // =========================================================== LIBRARY page
  function pageLibrary(main) {
    main.appendChild(h("h1", { text: "Topic library" }));
    main.appendChild(h("p", { class: "lede", text:
      "The library expands on its own: entities found in verified payloads become " +
      "candidate topics, two signals promote a candidate, and a topic that stops " +
      "producing signals is retired rather than deleted. A topic with zero verified " +
      "claims is shown as unsupported — it is never described." }));

    var q = "";
    var fam = "all";
    var fams = D.families;

    main.appendChild(section("families", "Families", fams.length,
      table(["Family", "Category", "The question", "Topics", "Verified claims", "Sources"],
        fams.map(function (f) {
          return tr([
            td(h("a", { href: "#" + f.slug, text: f.title })),
            td(short(f.category, 26)), td(f.question),
            tdn(f.topics), tdn(f.verifiedClaims),
            td(h("span", { class: "small", text: f.sources.join(", ") })),
          ]);
        }), { nums: [3, 4] })));

    var listHost = h("div", {});
    var toolbar = h("div", { class: "toolbar" });
    var search = h("input", { type: "search", placeholder: "Filter topics…", "aria-label": "Filter topics" });
    toolbar.appendChild(search);
    var chips = h("div", { style: "display:flex;gap:6px;flex-wrap:wrap" });
    toolbar.appendChild(chips);

    function chip(label, val, count) {
      return h("button", {
        class: "chip", type: "button", "aria-pressed": fam === val ? "true" : "false",
        onclick: function () { fam = val; render(); },
      }, [document.createTextNode(label), h("span", { class: "c", text: String(count) })]);
    }

    function render() {
      Array.prototype.slice.call(chips.children).forEach(function (c) { c.remove(); });
      var byFam = { all: D.topics.length };
      D.topics.forEach(function (t) { byFam[t.family] = (byFam[t.family] || 0) + 1; });
      chips.appendChild(chip("All", "all", D.topics.length));
      fams.forEach(function (f) {
        if (byFam[f.slug]) chips.appendChild(chip(f.title, f.slug, byFam[f.slug]));
      });
      Array.prototype.slice.call(chips.children).forEach(function (c) {
        c.setAttribute("aria-pressed", c.textContent.indexOf("") >= 0 ? c.getAttribute("aria-pressed") : "false");
      });

      Array.prototype.slice.call(listHost.children).forEach(function (c) { c.remove(); });
      var rows = D.topics.filter(function (t) {
        if (fam !== "all" && t.family !== fam) return false;
        if (!q) return true;
        return (t.title + " " + t.slug + " " + t.familyTitle + " " + (t.notes || "")).toLowerCase().indexOf(q) >= 0;
      });
      listHost.appendChild(h("p", { class: "small", text: "Showing " + rows.length + " of " + D.topics.length + " topics." }));
      if (!rows.length) { listHost.appendChild(empty("No topic matches.")); return; }

      rows.forEach(function (t) {
        // A claim supports a topic when the topic is its family bucket OR one
        // of its entity subjects.  Filtering on c.topic alone showed 127 of 132
        // entity topics as "no accepted claim" in the detail panel while their
        // badges carried 60+ claims — the same card contradicting itself.
        var claims = D.evidence.filter(function (c) {
          return c.topic === t.slug || (c.subjects || []).indexOf(t.slug) >= 0;
        });
        var legacy = Math.max(0, (t.creditedClaims || 0) - t.verifiedClaims);
        var body = h("div", { class: "body" }, [
          h("dl", { class: "kv" }, [
            h("dt", { text: "Status" }), h("dd", {}, [badge(t.status, t.status === "active" ? "ok" : (t.status === "retired" ? "mute" : "info"))]),
            h("dt", { text: "Family" }), h("dd", { text: t.familyTitle + " — " + t.question }),
            h("dt", { text: "Claim rows (recent window)" }), h("dd", { text: String(claims.length) }),
            h("dt", { text: "Verified claims" }), h("dd", { text: String(t.verifiedClaims) }),
            legacy > 0 ? h("dt", { text: "Credited (pre-v2)" }) : null,
            legacy > 0 ? h("dd", {}, [badge("+" + legacy + " credit", "info"),
              document.createTextNode(" — persisted before claim rows recorded subjects; kept as history, not counted as verified")]) : null,
            h("dt", { text: "Signals" }), h("dd", { text: String(t.signals) }),
            h("dt", { text: "Created" }), h("dd", { text: "cycle " + t.createdCycle + " · " + (t.firstSeenAt || "—") }),
            h("dt", { text: "Last signal" }), h("dd", { text: "cycle " + t.lastSignalCycle + " · " + ago(t.lastSeenAt) }),
            h("dt", { text: "Origin" }), h("dd", {}, [h("code", { text: t.origin || "—" }), t.originUrl ? document.createTextNode(" · ") : null, t.originUrl ? link(t.originUrl, "source") : null]),
            t.parent ? h("dt", { text: "Descends from" }) : null,
            t.parent ? h("dd", {}, [h("a", { href: "#" + t.parent, text: t.parent })]) : null,
            t.notes ? h("dt", { text: "Note" }) : null,
            t.notes ? h("dd", { text: t.notes }) : null,
          ]),
          h("h3", { text: "Claim rows naming this topic (" + claims.length + " of the recent window)" }),
          claims.length ? table(["Claim", "Kind", "Source", "Evidence"],
            claims.slice(0, 60).map(function (c) {
              var ev = (D.evidenceRows || {})[(c.evidenceIds || [])[0]] || {};
              return tr([
                td(h("a", { href: "evidence.html#claim-" + c.id, text: short(c.statement, 150) })),
                td(badge(c.kind, c.kind === "derived" ? "acc" : "mute")),
                td(h("code", { text: c.sourceId })),
                td(ev.url ? link(ev.url, "open", ev.url) : h("span", { class: "small", text: "derived" })),
              ]);
            })) : h("p", { class: "empty", text: "This topic has no accepted claim. It is listed so the gap is visible; nothing is asserted about it." }),
        ]);
        var det = h("details", { class: "row", id: encodeURIComponent(t.slug) }, [
          h("summary", {}, [
            h("span", { class: "t", text: t.title }),
            badge(t.status, t.status === "active" ? "ok" : (t.status === "retired" ? "mute" : "info")),
            badge(t.verifiedClaims + " claims", t.verifiedClaims ? "acc" : "crit"),
            badge(t.signals + " signals", "mute"),
            h("span", { class: "small", text: short(t.familyTitle, 30) }),
          ]),
          body,
        ]);
        listHost.appendChild(det);
      });
    }

    search.addEventListener("input", function () { q = search.value.toLowerCase().trim(); render(); });
    main.appendChild(section("topics", "Topics", D.topics.length, [toolbar, listHost]));
    render();
  }

  // ======================================================= LEADERBOARD page
  function pageLeaderboard(main) {
    var lb = D.leaderboard || {};
    main.appendChild(h("h1", { text: "Persona competition" }));
    main.appendChild(h("p", { class: "lede", text:
      "Each persona reads only the accepted ledger and issues a falsifiable forecast " +
      "about the next observation of a tracked metric. The following cycle the engine " +
      "looks up what actually happened and scores it. Nothing is scored that was not " +
      "forecast in advance." }));

    main.appendChild(h("div", { class: "note" }, [
      h("b", { text: "Qualification rule. " }),
      document.createTextNode(lb.qualification ? lb.qualification.rule : ""),
      document.createTextNode(" Null-model accuracy so far: "),
      h("b", { text: lb.nullAccuracy === null || lb.nullAccuracy === undefined ? "no scored forecast yet" : pct(lb.nullAccuracy) }),
      document.createTextNode(" over " + n(lb.nullScored) + " scored forecast(s)."),
    ]));

    var ranked = lb.ranked || [];
    main.appendChild(section("ranked", "Ranked", ranked.length,
      ranked.length ? table(["#", "Persona", "Thesis", "Issued", "All scored", "Paired", "Paired accuracy", "Paired null", "Mean Brier", "Skill"],
        ranked.map(function (r, i) {
          return tr([
            td(i + 1, "num"),
            td(h("b", { id: r.strategyId, text: r.name })),
            td(h("span", { class: "small", text: r.thesis })),
            tdn(r.issued), tdn(r.scored), tdn(r.pairedScored),
            td(pct(r.pairedAccuracy)), td(pct(r.pairedNullAccuracy)),
            td(r.meanBrier === null || r.meanBrier === undefined ? "—" : r.meanBrier.toFixed(4), "num"),
            td(h("span", { class: (r.skill || 0) >= 0 ? "up" : "down", text: signed((r.skill || 0) * 100, 1) }), "num"),
          ]);
        }), { nums: [0, 3, 4, 5, 6, 7, 8, 9] })
        : h("div", { class: "note warn", text: "No persona qualifies yet. See the qualification rule above — this is the honest state, not a failure." })));

    var unranked = lb.unranked || [];
    main.appendChild(section("unranked", "Unranked, with the reason", unranked.length,
      unranked.length ? table(["Persona", "Thesis", "Issued", "All scored", "Paired", "Why it is not ranked"],
        unranked.map(function (r) {
          return tr([
            td(h("b", { id: r.strategyId + "-u", text: r.name })),
            td(h("span", { class: "small", text: r.thesis })),
            tdn(r.issued), tdn(r.scored), tdn(r.pairedScored),
            td(r.unrankedReason || "—"),
          ]);
        }), { nums: [2, 3, 4] }) : empty("Every persona is ranked.")));

    var fc = (D.forecasts || []).slice().reverse().slice(0, 150);
    main.appendChild(section("forecasts", "Forecast log", (D.forecasts || []).length,
      fc.length ? table(["Cycle", "Persona", "Topic", "Metric", "Predicted", "P(up)", "Outcome", "Brier", "Basis"],
        fc.map(function (f) {
          return tr([
            tdn(f.cycle),
            td(h("code", { text: f.strategyId })),
            td(short(f.topic, 22)),
            td(h("code", { text: short(f.metric, 34) })),
            td(badge(f.direction, f.direction === "up" ? "ok" : (f.direction === "down" ? "crit" : "mute"))),
            td(f.probability.toFixed(2), "num"),
            td(f.scored ? badge(f.outcome, f.outcome === f.direction ? "ok" : "crit") : badge("pending", "mute")),
            td(f.brier === null || f.brier === undefined ? "—" : f.brier.toFixed(4), "num"),
            td(h("span", { class: "small", text: short(f.reason, 90) })),
          ]);
        }), { nums: [0, 5, 7] }) : empty("No forecast has been issued yet.")));

    var w = D.memory.strategyWeights || {};
    var wkeys = Object.keys(w);
    main.appendChild(section("weights", "Learned skill weights (drives S06_MemoryWeighted)", wkeys.length,
      wkeys.length ? table(["Persona", "Weight"], wkeys.sort().map(function (k) {
        return tr([td(h("code", { text: k })), td(w[k].toFixed(4), "num")]);
      }), { nums: [1] })
        : empty("No persona has been scored yet, so no weight exists. S06 issues nothing until it does.")));
  }

  // ============================================================= IDEAS page
  function pageIdeas(main) {
    main.appendChild(h("h1", { text: "Idea competition" }));
    main.appendChild(h("p", { class: "lede", text:
      "Ideas are generated by a fixed rule set over accepted claims and scored for " +
      "robustness. They persist: each cycle they are re-scored against the current " +
      "ledger, so one that keeps gaining corroboration climbs and one whose support " +
      "disappears sinks. An idea with no accepted claim behind it is not produced." }));

    var ideas = D.ideas || [];
    var kinds = {};
    ideas.forEach(function (i) { kinds[i.kind] = (kinds[i.kind] || 0) + 1; });

    main.appendChild(section("kinds", "Idea kinds", Object.keys(kinds).length,
      Object.keys(kinds).length ? table(["Kind", "Count"],
        Object.keys(kinds).sort(function (a, b) { return kinds[b] - kinds[a]; }).map(function (k) {
          return tr([td(h("code", { text: k })), tdn(kinds[k])]);
        }), { nums: [1] }) : empty("No idea yet.")));

    var weights = [
      ["evidence", "how many accepted claims stand behind it", 0.30],
      ["corroboration", "how many independent sources report it", 0.30],
      ["breadth", "how many topic families it spans", 0.15],
      ["freshness", "how recent the newest supporting claim is", 0.15],
      ["reproducibility", "whether a reader can re-fetch the source now", 0.10],
    ];
    main.appendChild(section("robustness", "How robustness is computed", null,
      table(["Component", "Weight", "Meaning"], weights.map(function (w) {
        return tr([td(h("code", { text: w[0] })), td(w[2].toFixed(2), "num"), td(w[1])]);
      }), { nums: [1] })));

    var host = h("div", {});
    ideas.forEach(function (i) {
      var comps = i.components || {};
      host.appendChild(h("details", { class: "row", id: i.id }, [
        h("summary", {}, [
          h("span", { class: "t", text: i.title }),
          badge(i.kind, "acc"),
          badge(i.status, i.status === "promoted" ? "ok" : (i.status === "retired" ? "mute" : "info")),
          h("span", { class: "small", text: "robustness " + i.robustness.toFixed(3) + " · seen " + i.appearances + "×" }),
        ]),
        h("div", { class: "body" }, [
          h("p", { text: i.statement }),
          h("dl", { class: "kv" }, [
            h("dt", { text: "Robustness" }), h("dd", {}, [
              h("div", { class: "bar" + (i.robustness < 0.3 ? " crit" : "") }, [h("i", { style: "width:" + Math.round(i.robustness * 100) + "%" })]),
              h("span", { class: "small", text: i.robustness.toFixed(4) }),
            ]),
            h("dt", { text: "Components" }), h("dd", { class: "small", text: Object.keys(comps).map(function (k) { return k + " " + comps[k].toFixed(2); }).join(" · ") }),
            h("dt", { text: "Sources" }), h("dd", { class: "small", text: (i.sources || []).join(", ") || "—" }),
            h("dt", { text: "Families" }), h("dd", { class: "small", text: (i.families || []).join(", ") || "—" }),
            h("dt", { text: "Lifecycle" }), h("dd", { class: "small", text: "first cycle " + i.firstSeenCycle + ", last cycle " + i.lastSeenCycle + ", " + i.appearances + " appearance(s)" }),
          ]),
          h("h3", { text: "Accepted claims behind this idea (" + (i.lineage || []).length + ")" }),
          (i.lineage || []).length ? h("p", { class: "small" }, (i.lineage || []).map(function (id) {
            return h("a", { href: "evidence.html#claim-" + id, text: id });
          }).reduce(function (acc, el, k) {
            if (k) acc.push(document.createTextNode("  ·  "));
            acc.push(el);
            return acc;
          }, [])) : h("p", { class: "empty", text: "No lineage. This is a coverage gap, not a claim." }),
          (i.urls || []).length ? h("h3", { text: "Sources to open" }) : null,
          (i.urls || []).length ? h("ul", {}, (i.urls || []).map(function (u) { return h("li", {}, [link(u, short(u, 90))]); })) : null,
          (i.history || []).length ? h("h3", { text: "Robustness history" }) : null,
          (i.history || []).length ? table(["Cycle", "Robustness", "Lineage"], (i.history || []).map(function (x) {
            return tr([tdn(x.cycle), td(x.robustness.toFixed(4), "num"), tdn(x.lineageSize)]);
          }), { nums: [0, 1, 2] }) : null,
        ]),
      ]));
    });
    main.appendChild(section("ideas-list", "Ideas, most robust first", ideas.length,
      ideas.length ? host : empty("No idea has a verified lineage yet.")));
  }

  // =========================================================== PROJECTS page
  function pageProjects(main) {
    var projects = D.projects || [];
    var catalog = D.projectCatalog || {};
    var categories = {};
    projects.forEach(function (p) {
      var name = p.category || "Uncategorized";
      (categories[name] = categories[name] || []).push(p);
    });
    function supersededHere(p) {
      // The catalog snapshot described this repository before the application on
      // this very page existed. Keep the historical row, but never call it current.
      return p.repo === "MasterSelfLearn";
    }
    var stale = projects.filter(function (p) {
      return p.proseStale || supersededHere(p);
    }).length;

    main.appendChild(h("h1", { text: "MasterSite project catalog — point-in-time audit" }));
    main.appendChild(h("p", { class: "lede", text:
      "The owner's MasterSite catalog, brought through the evidence gate as a point-in-time " +
      "artifact. This project verifies the catalog file and its Git blob hash; it does not " +
      "re-query all 52 repositories every cycle. Descriptions, commits, and Pages states are " +
      "therefore shown as MasterSite audit records, not guaranteed current facts." }));
    main.appendChild(h("div", { class: "stats" }, [
      stat("Catalog entries", projects.length, "latest accepted MasterSite artifact", "ok"),
      stat("Categories", Object.keys(categories).length, "owner interest map", ""),
      stat("Pages marked built", projects.filter(function (p) { return p.pagesStatus === "built"; }).length,
           "at each recorded catalog audit", ""),
      stat("Stale / superseded", stale,
           "upstream flags plus this repository's superseded row", stale ? "warn" : ""),
    ]));
    if (!projects.length) {
      main.appendChild(empty("No MasterSite catalog claim has passed the evidence gate yet. The next successful catalog read will populate this page."));
      return;
    }
    main.appendChild(h("div", { class: "note" }, [
      document.createTextNode("Catalog source: "),
      link(catalog.masterSiteUrl || D.meta.masterSiteUrl, catalog.source || "MasterSite"),
      document.createTextNode(". Each row carries its audit date and basis. “Not flagged stale” means only that MasterSite did not flag it at that audit; it is not a live freshness verdict from MasterSelfLearn."),
    ]));

    Object.keys(categories).sort().forEach(function (category) {
      var rows = categories[category].sort(function (a, b) {
        return String(a.title || a.repo).localeCompare(String(b.title || b.repo));
      }).map(function (p) {
        var title = h("div", {}, [
          link(p.pagesUrl, p.title || p.repo),
          h("div", { class: "small", text: p.repo || "" }),
        ]);
        var description = h("div", {}, [
          supersededHere(p) ? h("div", { class: "note warn", text:
            "Historical catalog description: superseded when this research system was implemented after the recorded audit." }) : null,
          h("div", { text: p.description || "No audited description recorded." }),
          p.flags && p.flags.length ? h("div", { class: "small warn-text", text: "Flags: " + p.flags.join("; ") }) : null,
        ]);
        var audit = h("details", {}, [
          h("summary", { text: p.lastVerified ? "catalog audit " + p.lastVerified : "recorded audit basis" }),
          h("p", { class: "small", text: p.verifiedBasis || "No narrative verification basis recorded." }),
          h("p", { class: "small", text: "Head " + (p.headSha || "—") + " · " +
            n(p.commits) + " commits · retrieved " + (p.retrievedAt || "—") +
            " · path " + (p.sourcePath || "—") }),
          h("p", {}, [link(p.sourceUrl, "API source"), document.createTextNode(" · "),
            h("a", { href: "evidence.html#claim-" + encodeURIComponent(p.claimId || ""), text: "accepted claim" })]),
        ]);
        return tr([td(title), td(description), td([
          badge(p.pagesStatus || "unreported", p.pagesStatus === "built" ? "ok" : "warn"),
          document.createTextNode(" "), badge(p.kind || "project", ""),
        ]), td(audit)]);
      });
      main.appendChild(section("project-" + category.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
        category, rows.length,
        table(["Project", "Catalog description (as audited)", "Pages (as audited)", "Audit"], rows)));
    });
  }

  // =========================================================== EVIDENCE page
  function pageEvidence(main) {
    main.appendChild(h("h1", { text: "Evidence ledger" }));
    main.appendChild(h("p", { class: "lede", text:
      "The most recent accepted-claim window, with source URL, source path, retained " +
      "integrity hash, and capture time; the full append-only ledger is linked below. " +
      "Wire and projection-only hashes are labelled separately. " +
      "Derived claims show the formula and the claim " +
      "ids they were computed from, so the arithmetic can be redone by hand." }));

    var kinds = D.claimKindCounts || {};
    main.appendChild(h("div", { class: "stats" }, [
      stat("Claims in ledger", n(D.claimTotal), "append-only JSONL", "ok"),
      stat("captured", n(kinds.captured), "read from a payload", ""),
      stat("derived", n(kinds.derived), "recorded arithmetic", ""),
      stat("negative", n(kinds.negative), "proof of absence", ""),
      stat("documented", n(kinds.documented), "operator's own record", ""),
      stat("Distinct evidence reads", n(D.evidenceTotal), n((D.evidence || []).length) + " claims trace to them", "ok"),
      stat("Gate rejections", n(D.gateRejectionsTotal || 0),
           n(D.gateRejectionWindow || 0) + " recent rows shown · append-only",
           (D.gateRejectionsTotal || 0) ? "warn" : "ok"),
    ]));

    var rej = D.gateRejections || [];
    main.appendChild(section("gate", "What the evidence gate rejected (recent window)",
      D.gateRejectionsTotal || rej.length,
      rej.length ? table(["Kind", "Source", "Reason"], rej.map(function (r) {
        return tr([td(badge(r.kind || "?", "crit")), td(h("code", { text: r.sourceId || "?" })), td(r.reason)]);
      })) : h("p", { class: "empty", text: "Nothing has been rejected. A permanent zero here would be suspicious — it would mean the gate never sees a claim without evidence." })));

    var rows = (D.evidence || []).slice().reverse();
    if ((D.claimTotal || 0) > (D.claimWindow || rows.length)) {
      main.appendChild(h("p", { class: "note", html:
        "Showing the most recent <b>" + n(D.claimWindow) + "</b> of <b>" + n(D.claimTotal) +
        "</b> claims. The site ships a window, not the whole history: the complete " +
        "append-only ledger is <code>data/claims.jsonl</code> in this repository, and " +
        "every number above is recomputed from all of it, not from what is shown here." }));
    }
    var kind = "all", src = "all", q = "";
    var host = h("div", {});
    var toolbar = h("div", { class: "toolbar" });
    var search = h("input", { type: "search", placeholder: "Search statements, fields, tags…", "aria-label": "Search claims" });
    var kindChips = h("div", { style: "display:flex;gap:6px;flex-wrap:wrap" });
    toolbar.appendChild(search); toolbar.appendChild(kindChips);

    function render() {
      Array.prototype.slice.call(kindChips.children).forEach(function (c) { c.remove(); });
      ["all", "captured", "derived", "negative", "documented"].forEach(function (k) {
        kindChips.appendChild(h("button", {
          class: "chip", type: "button", "aria-pressed": kind === k ? "true" : "false",
          onclick: function () { kind = k; render(); },
        }, [document.createTextNode(k), h("span", { class: "c", text: k === "all" ? String(rows.length) : String((kinds[k] || 0)) })]));
      });

      Array.prototype.slice.call(host.children).forEach(function (c) { c.remove(); });
      var f = rows.filter(function (c) {
        if (kind !== "all" && c.kind !== kind) return false;
        if (src !== "all" && c.sourceId !== src) return false;
        if (!q) return true;
        return (c.statement + " " + c.field + " " + (c.tags || []).join(" ") + " " + c.topic).toLowerCase().indexOf(q) >= 0;
      }).slice(0, 400);
      host.appendChild(h("p", { class: "small", text: "Showing " + f.length + " of " + rows.length + " most recent claims (ledger holds " + n(D.claimTotal) + " in total)." }));
      if (!f.length) { host.appendChild(empty("No claim matches.")); return; }

      f.forEach(function (c) {
        var ev = (D.evidenceRows || {})[(c.evidenceIds || [])[0]] || null;
        host.appendChild(h("details", { class: "row", id: "claim-" + c.id }, [
          h("summary", {}, [
            h("code", { text: c.id }),
            badge(c.kind, c.kind === "derived" ? "acc" : "mute"),
            h("span", { text: short(c.statement, 150) }),
          ]),
          h("div", { class: "body" }, [
            h("dl", { class: "kv" }, [
              h("dt", { text: "Topic" }), h("dd", {}, [h("a", { href: "library.html#" + encodeURIComponent(c.topic), text: c.topic })]),
              h("dt", { text: "Field" }), h("dd", {}, [h("code", { text: c.field || "—" })]),
              c.sourcePath ? h("dt", { text: "Source path" }) : null,
              c.sourcePath ? h("dd", {}, [h("code", { text: c.sourcePath })]) : null,
              (c.subjects || []).length ? h("dt", { text: "Subjects" }) : null,
              (c.subjects || []).length ? h("dd", { class: "small", text: c.subjects.join(", ") }) : null,
              h("dt", { text: "Value" }), h("dd", { text: (typeof c.value === "object" ? JSON.stringify(c.value) : String(c.value)) + (c.unit ? " " + c.unit : "") }),
              h("dt", { text: "Source" }), h("dd", {}, [h("code", { text: c.sourceId }), ev ? document.createTextNode("  ·  captured " + (ev.capturedAt || "—")) : null]),
              ev ? h("dt", { text: "Read from" }) : null,
              ev ? h("dd", {}, [link(ev.url, short(ev.url, 100)),
                ev.finalUrl && ev.finalUrl !== ev.url ? document.createTextNode(" → ") : null,
                ev.finalUrl && ev.finalUrl !== ev.url ? link(ev.finalUrl, "final URL") : null]) : null,
              ev ? h("dt", { text: "HTTP / bytes" }) : null,
              ev ? h("dd", { text: (ev.status === null || ev.status === undefined ? "—" : ev.status) +
                " · " + n(ev.rawBytes) + " B · " + (ev.contentType || "type unrecorded") +
                " · mode " + ev.captureMode }) : null,
              ev ? h("dt", { text: "Integrity / SHA-256" }) : null,
              ev ? h("dd", {}, [
                badge(ev.integrity || "missing", ev.integrity === "wire" ? "ok" :
                  (ev.integrity === "projection" ? "warn" : "crit")),
                document.createTextNode(" "),
                h("span", { class: "hash", text: ev.sha256 || "—" }),
                ev.truncated ? badge("truncated — unusable", "crit") : null,
              ]) : null,
              c.formula ? h("dt", { text: "Formula" }) : null,
              c.formula ? h("dd", {}, [h("code", { text: c.formula })]) : null,
              (c.computedFrom || []).length ? h("dt", { text: "Computed from" }) : null,
              (c.computedFrom || []).length ? h("dd", {}, (c.computedFrom || []).map(function (id) {
                return h("a", { href: "#claim-" + id, text: id });
              })) : null,
              (c.tags || []).length ? h("dt", { text: "Tags" }) : null,
              (c.tags || []).length ? h("dd", { class: "small", text: (c.tags || []).join(", ") }) : null,
            ]),
          ]),
        ]));
      });
    }
    search.addEventListener("input", function () { q = search.value.toLowerCase().trim(); render(); });
    main.appendChild(section("claims", "Claims", D.claimTotal, [toolbar, host]));
    render();
  }

  // ============================================================ SOURCES page
  function pageSources(main) {
    main.appendChild(h("h1", { text: "Source registry" }));
    main.appendChild(h("p", { class: "lede", text:
      "Every source names its operator and a documentation URL you can open to check " +
      "the endpoint contract. A source is promoted to verified only by a recorded " +
      "live read — never by hand. A failed read itself produces no fresh claim; an " +
      "older exact-URL seed, when available, is labelled seed-fallback." }));

    var src = D.sources || [];
    var verified = src.filter(function (s) { return s.status === "verified-live-read"; }).length;
    var blocked = src.filter(function (s) { return s.status === "blocked"; }).length;
    var registered = src.filter(function (s) { return s.status === "registered"; }).length;

    main.appendChild(h("div", { class: "stats" }, [
      stat("Registered", n(src.length), "each provenance tier is explicit", ""),
      stat("Verified", n(verified), "by a recorded live read", "ok"),
      stat("Blocked", n(blocked), "last conclusive read failed", blocked ? "bad" : "ok"),
      stat("Never read", n(registered), "first read pending", registered ? "warn" : "ok"),
      stat("Excluded", n((D.keyedExcluded || []).length), "require an API key", "warn"),
      stat("Coverage gaps", n((D.categoriesWithoutSource || []).length), "documented partial or missing coverage", "warn"),
    ]));

    main.appendChild(section("registry", "Registry", src.length,
      table(["Source", "Operator", "Trust", "Status", "Reads", "Last read", "HTTP", "Documentation"],
        src.map(function (s) {
          return tr([
            td(h("span", { id: s.id }, [h("b", { text: s.name })])),
            td(short(s.operator, 40)),
            td(badge(s.trustTier || "unclassified",
              (s.trustTier || "").indexOf("undocumented") >= 0 ||
              (s.trustTier || "").indexOf("third-party") >= 0 ? "warn" : "mute")),
            td(badge(s.status, s.status === "verified-live-read" ? "ok" : (s.status === "blocked" ? "crit" : "warn"))),
            tdn(s.liveReads), td(s.lastReadAt ? ago(s.lastReadAt) : "—"),
            td(s.lastStatus === null || s.lastStatus === undefined ? "—" : String(s.lastStatus), "num"),
            td(h("span", {}, [link(s.docsUrl, "docs"), document.createTextNode(" · "), link(s.probeUrl, "probe")])),
          ]);
        }), { nums: [4, 6] })));

    var health = D.sourceHealth || {};
    if (!health.ran) {
      main.appendChild(h("div", { class: "note warn" }, [
        h("b", { text: "No probe has recorded a read yet. " }),
        document.createTextNode(health.reason ||
          "Run `python3 tools/probe_sources.py`. Until a probe records a read, no " +
          "source status on this page is backed by evidence."),
      ]));
    } else {
      var hrows = health.results || [];
      var nEgress = hrows.filter(function (r) { return r.egressBlocked; }).length;
      main.appendChild(section("probe", "Last recorded source-health check", hrows.length,
        h("div", {}, [
          h("p", { class: "small", text:
            "Recorded " + (health.generatedAt || "—") + " in mode `" + (health.mode || "?") +
            "` by `" + (health.lastWriter || "probe") + "`. " +
            n(health.ok) + " read successfully, " + n(health.failed) +
            " recorded a health-affecting failure, " + n(health.inconclusive) +
            " reached no verdict. A source's status on this page comes from this " +
            "table and from nothing else." }),
          health.egressBlocked ? h("div", { class: "note warn" }, [
            h("b", { text: "This probe could not reach the network for " + n(nEgress) +
              " of " + n(hrows.length) + " sources. " }),
            document.createTextNode("Every one of those failures was a TLS session " +
              "closed before any HTTP status arrived, which is a property of the " +
              "machine that ran the probe, not of those services. None of them is " +
              "marked blocked, and nothing here claims any of them is down. " +
              "Re-run the probe from a runner with unrestricted egress."),
          ]) : null,
          table(["Source", "Verdict", "HTTP", "Bytes", "ms", "SHA-256 (16)", "Checked", "Detail"],
            hrows.map(function (r) {
              var verdict = r.ok ? "read ok"
                : (!r.verdict ? "no verdict — " + (r.inconclusiveReason ||
                    (r.egressBlocked ? "runner-egress" : "inconclusive"))
                  : "FAILED");
              return tr([
                td(h("span", {}, [h("a", { href: "#" + r.id, text: r.id })])),
                td(badge(verdict, r.ok ? "ok" : (!r.verdict ? "mute" : "crit"))),
                td(r.httpStatus === null || r.httpStatus === undefined ? "—" : String(r.httpStatus), "num"),
                tdn(r.bytes), tdn(r.elapsedMs),
                td(h("span", { class: "hash", text: r.sha256 || "—" })),
                td(r.checkedAt ? ago(r.checkedAt) : "—"),
                td(h("span", { class: "small", text: r.error || (r.ok ? "—" : "") })),
              ]);
            }), { nums: [2, 3, 4] }),
        ])));
    }

    var notes = src.filter(function (s) { return s.notes || s.docsNote; });
    main.appendChild(section("notes", "Recorded endpoint notes and findings", notes.length,
      notes.length ? table(["Source", "Note"], notes.map(function (s) {
        return tr([td(h("code", { text: s.id })), td(h("span", { class: "small", text: (s.notes || "") + (s.docsNote ? " — " + s.docsNote : "") }))]);
      })) : empty("No notes recorded.")));

    var seeds = D.seedCaptures || [];
    main.appendChild(section("seeds", "Seed captures (bootstrap evidence)", seeds.length,
      seeds.length ? table(["File", "Captured (UTC)", "HTTP", "Bytes", "SHA-256", "Mode", "URL"],
        seeds.map(function (s) {
          return tr([
            td(h("code", { text: s.file })), td(s.capturedAt),
            td(s.httpStatus === null || s.httpStatus === undefined ? "—" : String(s.httpStatus), "num"),
            tdn(s.rawBytes), td(h("span", { class: "hash", text: short(s.payloadSha256 || "", 20) })),
            td(badge(s.captureMode || "?", s.wireHashVerifiable === false ? "warn" : "mute")),
            td(link(s.url, short(s.url, 50))),
          ]);
        }), { nums: [2, 3] }) : empty("No seed capture.")));

    var keyed = D.keyedExcluded || [];
    main.appendChild(section("excluded", "Excluded for requiring a key — and why", keyed.length,
      keyed.length ? table(["Source", "Documentation", "Reason it was rejected"], keyed.map(function (s) {
        return tr([td(h("b", { text: s.name })), td(link(s.docsUrl, "docs")), td(s.reason)]);
      })) : empty("Nothing excluded.")));

    var gaps = D.categoriesWithoutSource || [];
    main.appendChild(section("gaps", "Documented interest-category coverage gaps", gaps.length,
      gaps.length ? table(["Category", "Missing or partial coverage"], gaps.map(function (s) {
        return tr([td(h("b", { text: s.category })), td(s.gap)]);
      })) : empty("No interest-category coverage gap is currently recorded.")));

    var prof = D.profile || {};
    main.appendChild(section("profile", "Derived interest profile", null,
      prof.available ? h("div", {}, [
        h("p", { class: "small", text: "Scored from the owner's own published corpus, not asserted. " + n(prof.repoCount) + " repositories read from " + (prof.source || "") + " at " + (prof.capturedAt || "—") + " (sha256 " + short(prof.payloadSha256 || "", 20) + ")." }),
        table(["Family", "Score", "Matching keywords"], Object.keys(prof.categories || {}).sort(function (a, b) {
          return prof.categories[b] - prof.categories[a];
        }).map(function (k) {
          return tr([td(k), td(prof.categories[k].toFixed(2), "num"),
            td(h("span", { class: "small", text: ((prof.categoryKeywords || {})[k] || []).join(", ") || "—" }))]);
        }), { nums: [1] }),
      ]) : h("div", { class: "note crit", text: "The interest profile could not be built: " + (prof.reason || "unknown reason") + ". No profile was invented." })));
  }

  // ====================================================== IRREGULARITIES page
  function pageIrregularities(main) {
    var counts = D.irregularityCounts || {};
    main.appendChild(h("h1", { text: "Flagged irregularities" }));
    main.appendChild(h("p", { class: "lede", text:
      "Anything the engine could not resolve, anything that disagreed with itself, and " +
      "anything it refuses to claim. Standing entries are structural limits of this " +
      "project rather than transient failures; they do not auto-resolve, because they " +
      "need to keep being seen." }));

    main.appendChild(h("div", { class: "stats" }, [
      stat("Registered", n(counts.total), "", ""),
      stat("Critical", n(counts.critical), "", counts.critical ? "bad" : "ok"),
      stat("Warn", n(counts.warn), "", counts.warn ? "warn" : "ok"),
      stat("Info", n(counts.info), "", ""),
      stat("Open", n(counts.open), "", counts.open ? "warn" : "ok"),
      stat("Standing", n(counts.standing), "structural limits", ""),
    ]));

    var sev = "all";
    var host = h("div", {});
    var toolbar = h("div", { class: "toolbar" });

    function render() {
      Array.prototype.slice.call(toolbar.children).forEach(function (c) { c.remove(); });
      var groups = { all: D.irregularities.length };
      ["critical", "warn", "info"].forEach(function (s) {
        groups[s] = D.irregularities.filter(function (i) { return i.severity === s; }).length;
      });
      ["all", "critical", "warn", "info"].forEach(function (s) {
        toolbar.appendChild(h("button", {
          class: "chip", type: "button", "aria-pressed": sev === s ? "true" : "false",
          onclick: function () { sev = s; render(); },
        }, [document.createTextNode(s), h("span", { class: "c", text: String(groups[s]) })]));
      });

      Array.prototype.slice.call(host.children).forEach(function (c) { c.remove(); });
      var rows = D.irregularities.filter(function (i) { return sev === "all" || i.severity === sev; });
      if (!rows.length) { host.appendChild(empty("No irregularity in this group.")); return; }
      rows.forEach(function (i) {
        host.appendChild(h("details", { class: "row", id: i.id }, [
          h("summary", {}, [
            h("code", { text: i.id }),
            badge(i.severity, i.severity),
            h("span", { class: "t", text: i.title }),
            badge(i.status, i.status === "open" ? "warn" : "mute"),
            i.standing ? badge("standing", "mute") : null,
          ]),
          h("div", { class: "body" }, [
            h("p", { text: i.detail }),
            h("dl", { class: "kv" }, [
              h("dt", { text: "First seen" }), h("dd", { text: "cycle " + i.firstSeenCycle + " · " + (i.firstSeenAt || "—") }),
              h("dt", { text: "Last seen" }), h("dd", { text: "cycle " + i.lastSeenCycle + " · " + (i.lastSeenAt || "—") }),
              h("dt", { text: "Occurrences" }), h("dd", { text: String(i.occurrences) }),
              i.sourceId ? h("dt", { text: "Source" }) : null,
              i.sourceId ? h("dd", {}, [h("a", { href: "sources.html#" + i.sourceId, text: i.sourceId })]) : null,
              i.topic ? h("dt", { text: "Topic" }) : null,
              i.topic ? h("dd", {}, [h("a", { href: "library.html#" + encodeURIComponent(i.topic), text: i.topic })]) : null,
              i.repro ? h("dt", { text: "Reproduce" }) : null,
              i.repro ? h("dd", {}, [h("code", { text: i.repro })]) : null,
            ]),
          ]),
        ]));
      });
    }
    main.appendChild(section("register", "Register", counts.total, [toolbar, host]));
    render();
  }

  // ============================================================== CYCLES page
  function pageCycles(main) {
    main.appendChild(h("h1", { text: "Cycle history" }));
    main.appendChild(h("p", { class: "lede", text:
      "One row per unattended run, with its network accounting. A cycle that read " +
      "nothing still publishes, and publishes nothing new — it does not fill the gap." }));

    var cycles = (D.cycles || []).slice().reverse();
    main.appendChild(section("history", "Cycles", D.cyclesTotal,
      cycles.length ? table(["Cycle", "At (UTC)", "Mode", "Reads ok/fail", "Planned/dropped", "Bytes", "New claims", "Rejected", "Topics", "Forecasts", "Scored", "Waiting", "Ideas", "Flags", "ms", "Result"],
        cycles.map(function (c) {
          return tr([
            tdn(c.cycle), td(c.at), td(h("code", { text: c.mode })),
            td(c.fetchOk + " / " + c.fetchFailed, "num"),
            // A cycle row written before the plan was counted says so rather than
            // showing a 0 the plan never reported.
            td(n(c.tasksPlanned) + " / " + n(c.tasksDropped), "num"),
            tdn((c.net || {}).bytesIn),
            tdn(c.claimsNew), tdn(c.claimsRejected), tdn(c.topicsTotal),
            tdn(c.forecastsIssued), tdn(c.forecastsScored), tdn(c.forecastsPending),
            tdn(c.ideas),
            tdn(c.irregularitiesOpen),
            // Cycles 1-14 recorded durationMs=0: the clock was read after the row
            // was written. That ordering is fixed; a recorded 0 is not a measured
            // duration, so it is shown as a dash rather than as a number.
            td(c.durationMs ? String(c.durationMs) : "—", "num"),
            td(c.ok ? badge("ok", "ok") : badge("ERROR", "crit")),
          ]);
        }), { nums: [0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] }) : empty("No cycle has run yet.")));

    var rel = D.memory.sourceReliability || {};
    var keys = Object.keys(rel).sort();
    main.appendChild(section("reliability", "Source reliability (EMA of probe success)", keys.length,
      keys.length ? table(["Source", "EMA", "Reading"], keys.map(function (k) {
        var v = rel[k];
        return tr([
          td(h("code", { text: k })), td(v.toFixed(3), "num"),
          td(h("div", { class: "bar" + (v < 0.5 ? (v < 0.2 ? " crit" : " warn") : "") }, [h("i", { style: "width:" + Math.round(v * 100) + "%" })])),
        ]);
      }), { nums: [1] }) : empty("No probe has run yet.")));

    var net = D.report.net || {};
    main.appendChild(section("net", "Last cycle network accounting", null,
      h("dl", { class: "kv" }, [
        h("dt", { text: "Requests" }), h("dd", { text: n(net.requests) }),
        h("dt", { text: "OK / failed" }), h("dd", { text: n(net.ok) + " / " + n(net.failed) }),
        h("dt", { text: "Rate limited" }), h("dd", { text: n(net.rateLimited) }),
        h("dt", { text: "Bytes" }), h("dd", { text: n(net.bytesIn) }),
        h("dt", { text: "Total time" }), h("dd", { text: n(net.msTotal) + " ms" }),
        h("dt", { text: "By host" }), h("dd", { class: "small", text: Object.keys(net.byHost || {}).map(function (k) { return k + " " + net.byHost[k]; }).join(" · ") || "—" }),
      ])));
  }

  // ========================================================= METHODOLOGY page
  function pageMethodology(main) {
    main.appendChild(h("h1", { text: "How it thinks — and where it stops" }));

    var blocks = [
      ["1. What “thinks” means here", [
        h("p", { text: "There is no language model in this loop and no API key anywhere in the repository. The reasoning stage is a fixed rule set over the accepted ledger: trend deltas, velocity, corroboration counts, acceleration, cross-family presence, and counters moving between cycles. Every published sentence is a template whose slots are filled from claim values." }),
        h("p", { text: "That is a deliberate trade. It costs novelty — the engine will not invent a framing nobody wrote down — and buys auditability: any number on this site can be recomputed from the ledger with one command. A model with an API key would need a secret, and adding a secret is manual input, which the brief rules out." }),
      ]],
      ["2. The anti-hallucination contract", [
        h("ol", {}, [
          "No evidence, no claim. Ledger.accept rejects a captured, documented or negative claim with no evidence row, and a derived claim with no lineage or formula. Rejections are counted and published.",
          "Unreadable is not unknown. A conclusive source failure is recorded; caller mistakes, local response caps, and runner egress produce no source-health verdict. A failed response yields no fresh claim. An exact-URL seed can only reappear as an explicitly stale seed-fallback.",
          "Yesterday's arithmetic is re-checked today. Every derived claim is recomputed from its recorded inputs each cycle; a mismatch is a drift irregularity and both numbers are shown.",
          "Nothing is inferred from a model's memory. Every fact traces to a URL that was actually read, with a hash.",
          "Gaps are printed. Topics with no accepted claims, families with no source that can answer their question, and sources excluded for needing a key are all listed with the reason.",
        ].map(function (t) { return h("li", { text: t }); })),
      ]],
      ["3. The cycle", [
        table(["Stage", "Module", "What it does"], [
          ["Plan", "msl/tasks.py", "Derives the reading list from the current library, so last cycle's topics get deeper reads now"],
          ["Collect", "msl/http.py", "Reads each URL. Returns bytes or a recorded failure, never a silent empty"],
          ["Verify", "msl/evidence.py", "The gate. Unsupported claims are rejected and the rejection is logged"],
          ["Discover", "msl/topics.py", "Entities in the payloads become candidate topics; two signals promote one"],
          ["Reason", "msl/reason.py", "Deterministic arithmetic, plus a recheck of every previous derivation"],
          ["Compete", "msl/strategies.py, msl/ideas.py", "Personas forecast; ideas are scored for robustness and carried forward"],
          ["Learn", "msl/learn.py", "Skill and reliability folded into memory; lessons counted from the ledger"],
          ["Publish", "msl/sitegen.py, msl/docs.py", "Site and docs regenerated from the same objects"],
        ].map(function (r) {
          return tr([td(h("b", { text: r[0] })), td(h("code", { text: r[1] })), td(r[2])]);
        })),
      ]],
      ["4. What a persona can be asked to predict", [
        h("p", { text: "Two kinds of target, scored by one rule. A magnitude — a star count, an index, an event count — is predicted up, down or flat. An identity — a release version, a release tag, a repository's primary language or its archived state — has no up or down, so the question is whether the next observation differs from this one, and “flat” means “unchanged”." }),
        h("p", { text: "Both are knowable one cycle later from the same ledger, and both are scored the same way: the outcome is read from an observation recorded in a later cycle, never from the forecast's own reasoning. S07_ChangeHazard answers the identity question from the subject's own history — how often its version or tag has changed so far — with Laplace smoothing, because a subject that has never changed has not earned a probability of zero." }),
        h("p", { text: "A forecast that waits for an observation that never arrives does not disappear quietly: pending forecasts are counted, and ones whose metric has stopped being observed are reported as unscoreable rather than kept as if something were still coming." }),
      ]],
      ["5. Why the competition is scored the way it is", [
        h("p", { text: "Paired skill, not raw accuracy, is the headline number. For each persona, only metric/cycle targets that S10_Persistence also forecast are compared; skill is that persona's accuracy minus persistence accuracy on those exact targets. Comparing each persona with the null's global, differently mixed target set would be invalid." }),
        h("p", { text: "A persona needs " + (D.leaderboard.qualification || {}).minScoredForecasts + " paired scored forecasts before it is ranked. Below that it is reported UNRANKED with the reason. It is never shown at 0%, which would present an untested design as a losing one." }),
      ]],
      ["6. Known limits", (D.keyedExcluded || []).length ? [
        h("ul", {}, [
          // Counts and names are read from the registry via site.js, never typed:
          // this list said "Three interest categories" while the registry held four,
          // and a limit that is out of date is a limit nobody can trust.
          h("li", { text: (D.keyedExcluded || []).length + " useful sources are excluded because they need an API key (" +
            (D.keyedExcluded || []).map(function (s) { return s.name; }).join(", ") +
            "). Each is listed on the Sources page with the reason." }),
          h("li", { text: (D.categoriesWithoutSource || []).length + " interest categories — " +
            (D.categoriesWithoutSource || []).map(function (c) { return c.category; }).join(", ") +
            " — have documented missing or partial coverage. No claim is made beyond the registered source surface." }),
          h("li", { text: "Some league feeds are undocumented public endpoints (no operator contract, no versioning promise). A claim built from one carries an “undocumented” tag, so the claim itself says what it rests on." }),
          h("li", { text: "GitHub has no trending API. The Search API sorted by stars over a created window is a reproducible substitute, not the same thing." }),
          h("li", { text: "Seed captures taken by an interactive or projected read are not wire-hash verifiable; those rows are marked projection-only and remain a disclosed historical limitation." }),
        ]),
        h("p", {}, [document.createTextNode("Full list: "), h("a", { href: "ROADMAP.md", text: "ROADMAP.md" }), document.createTextNode(".")]),
      ] : [h("p", { text: "See ROADMAP.md." })]],
      ["7. Reproduce any number", [
        h("pre", {}, [h("code", { text:
          "python3 -m msl.cli cycle --offline   # rebuild every artifact from data/seed/\n" +
          "python3 -m msl.cli verify-claims     # recheck every derived claim\n" +
          "python3 -m msl.cli probe             # live-read every registered source\n" +
          "python3 -m msl.cli gate-report       # what the gate rejected\n" +
          "python3 -m unittest discover -s tests" })]),
        h("p", { class: "small", text: "A number on this site that you cannot reproduce with one of those commands is a defect. Report it as an irregularity rather than editing the number." }),
      ]],
    ];

    blocks.forEach(function (b, i) {
      main.appendChild(section("m" + i, b[0], null, b[1]));
    });
  }

  // ------------------------------------------------------------------ boot
  var ROUTES = {
    "index.html": pageToday, "library.html": pageLibrary,
    "projects.html": pageProjects,
    "leaderboard.html": pageLeaderboard, "ideas.html": pageIdeas,
    "evidence.html": pageEvidence, "sources.html": pageSources,
    "irregularities.html": pageIrregularities, "cycles.html": pageCycles,
    "methodology.html": pageMethodology,
  };

  document.addEventListener("DOMContentLoaded", function () {
    shell();
    var main = document.getElementById("main");
    if (!main) return;
    var page = document.body.getAttribute("data-page") || "index.html";
    var fn = ROUTES[page];
    if (!fn) { main.appendChild(empty("Unknown page: " + page)); return; }
    if (!D) { noData(main); return; }
    try {
      fn(main);
    } catch (e) {
      main.appendChild(h("div", { class: "note crit", html:
        "<b>Render error on " + page + ".</b> The page refuses to draw a partial view, " +
        "because half a table of numbers is worse than none: <code>" +
        String(e && e.message ? e.message : e).replace(/[<>&]/g, "") + "</code>" }));
    }
    // deep links open their row
    if (location.hash) {
      var el = document.getElementById(decodeURIComponent(location.hash.slice(1)));
      if (el) {
        if (el.tagName === "DETAILS") el.open = true;
        el.scrollIntoView({ block: "start" });
      }
    }
  });
})();
