"""MasterSelfLearn (MSL) — an autonomous, evidence-first research engine.

Design contract (enforced in code, not just in prose):

1. Nothing enters the knowledge library without an ``Evidence`` record pointing at
   a real URL that was actually read, or an arithmetic derivation from claims that
   themselves have one.  ``evidence.Ledger.accept`` is the single gate.
2. A source that could not be read produces a recorded failure, never a guess.
3. Every derived number records the claim ids and the formula it came from, so a
   later pass can recompute it and flag drift.
4. The engine never asks a human for input.  Anything it cannot resolve becomes an
   entry in the irregularity register for the owner to read.
"""

__version__ = "0.1.0"

#: Machine-readable counts block.  Regenerated by ``msl.pipeline`` on every cycle;
#: never edited by hand.  Tools and the site read this instead of the prose.
AUTO_COUNTS = {}
