"""Memory — what the engine remembers between cycles, and how it changes its mind.

Everything here is a number derived from the ledger.  There is no free-text
"belief" store, because a belief that cannot be recomputed cannot be audited.

``data/memory.json`` holds:

* ``strategyWeights``  EMA of each persona's measured skill (drives S06)
* ``sourceReliability`` EMA of each source's probe success rate
* ``topicInterest``    per-topic signal history, which decides promotion/retirement
* ``lessons``          rules the engine has *derived* about its own track record

``lessons`` is the interesting one: it is generated by counting, not by
reflection — e.g. "topics corroborated by ≥2 sources persisted N× longer than
single-source topics" — and each lesson carries the counts that produced it.
"""
from __future__ import annotations

import json
import pathlib
from typing import Any, Dict, List, Optional

from . import config

ALPHA = 0.25


def empty_memory() -> Dict[str, Any]:
    return {
        "cyclesRun": 0,
        "lastCycleAt": "",
        "strategyWeights": {},
        "sourceReliability": {},
        "topicInterest": {},
        "lessons": [],
        "consecutiveCycleFailures": 0,
        "history": [],
    }


def load(data_dir: Optional[pathlib.Path] = None) -> Dict[str, Any]:
    p = pathlib.Path(data_dir or config.DATA) / "memory.json"
    m = empty_memory()
    if not p.exists():
        return m
    try:
        stored = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return m
    if isinstance(stored, dict):
        m.update(stored)
    return m


def save(memory: Dict[str, Any], data_dir: Optional[pathlib.Path] = None) -> None:
    d = pathlib.Path(data_dir or config.DATA)
    d.mkdir(parents=True, exist_ok=True)
    path = d / "memory.json"
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(memory, indent=1, sort_keys=True,
                              allow_nan=False) + "\n", encoding="utf-8")
    tmp.replace(path)


def update_source_reliability(memory: Dict[str, Any], outcomes: Dict[str, bool]) -> Dict[str, Any]:
    """EMA of per-source probe success.  1.0 = always readable, 0.0 = never."""
    rel = dict(memory.get("sourceReliability") or {})
    for sid, ok in outcomes.items():
        prev = rel.get(sid, 0.5)
        rel[sid] = round(prev * (1 - ALPHA) + (1.0 if ok else 0.0) * ALPHA, 6)
    memory["sourceReliability"] = rel
    return memory


def update_topic_interest(memory: Dict[str, Any], signals: Dict[str, int], cycle: int) -> Dict[str, Any]:
    ti = dict(memory.get("topicInterest") or {})
    for slug, n in signals.items():
        cur = ti.get(slug)
        if not isinstance(cur, dict):
            cur = {"ema": 0.0, "seen": 0, "lastCycle": 0, "peak": 0.0}
        cur["ema"] = round(cur["ema"] * (1 - ALPHA) + float(n) * ALPHA, 4)
        cur["seen"] = int(cur.get("seen", 0)) + 1
        cur["lastCycle"] = cycle
        cur["peak"] = max(float(cur.get("peak", 0.0)), cur["ema"])
        ti[slug] = cur
    memory["topicInterest"] = ti
    return memory


def derive_lessons(memory: Dict[str, Any], ledger, library, ideas) -> List[Dict[str, Any]]:
    """Count the engine's own track record and write down what the counts say.

    Each lesson is a statement plus the integers it came from.  A lesson with no
    supporting count is not written.
    """
    out: List[Dict[str, Any]] = []
    claims = ledger.claims
    if not claims:
        return out

    # L1 — what does multi-source corroboration actually predict?
    #
    # This used to bucket topics by the sources seen in ``c.topic`` alone.  Only
    # the family slugs ever appear there, every family has ``signals == 1``, and
    # the lesson confidently published "1.00 signals against 1.00 signals — a
    # ratio of 1.00×" as if it were a finding.  Entity attribution lives in
    # ``c.subjects`` (schema v2), so the buckets must be built from
    # topic+subjects, and derived claims are excluded because ``source_id ==
    # "derived"`` is our own arithmetic, not a second witness.
    per_topic_srcs: Dict[str, set] = {}
    per_topic_rows: Dict[str, int] = {}
    legacy_rows_no_subjects = 0
    for c in claims:
        if c.source_id == "derived":
            continue
        if not c.subjects:
            legacy_rows_no_subjects += 1
        for slug in dict.fromkeys([c.topic] + list(c.subjects)):
            if not slug:
                continue
            per_topic_srcs.setdefault(slug, set()).add(c.source_id)
            per_topic_rows[slug] = per_topic_rows.get(slug, 0) + 1
    multi = [t for t in library.topics.values()
             if len(per_topic_srcs.get(t.slug, set())) >= 2]
    single = [t for t in library.topics.values()
              if len(per_topic_srcs.get(t.slug, set())) == 1]
    if multi and single:
        sig_m = sum(t.signals for t in multi) / len(multi)
        sig_s = sum(t.signals for t in single) / len(single)
        rows_m = sum(per_topic_rows.get(t.slug, 0) for t in multi) / len(multi)
        rows_s = sum(per_topic_rows.get(t.slug, 0) for t in single) / len(single)
        claims_phrase = (f"{rows_m / rows_s:.1f}× more accepted claim rows on average "
                         f"({rows_m:.0f} vs {rows_s:.0f})" if rows_s > 0 else
                         f"accepted claim rows ({rows_m:.0f} vs none)")
        signals_phrase = (f"not more discovery signals ({sig_m:.1f} vs {sig_s:.1f})"
                          if sig_m <= sig_s else
                          f"and more discovery signals ({sig_m:.1f} vs {sig_s:.1f})")
        out.append({
            "id": "L1",
            "statement": (f"Topics corroborated by two or more independent sources hold "
                          f"{claims_phrase} than single-source topics, but {signals_phrase}. "
                          f"Entity attribution is row-provable only from schema v2, and "
                          f"{legacy_rows_no_subjects:,} accepted rows predate it, so "
                          f"single-source buckets may understate older support."),
            "counts": {"multiSourceTopics": len(multi), "singleSourceTopics": len(single),
                       "meanClaimRowsMulti": round(rows_m, 2),
                       "meanClaimRowsSingle": round(rows_s, 2),
                       "meanSignalsMulti": round(sig_m, 2),
                       "meanSignalsSingle": round(sig_s, 2),
                       "legacyRowsWithoutSubjects": legacy_rows_no_subjects},
            "implication": ("Corroboration predicts evidence depth, not signal frequency: "
                            "the discovery stage still requires "
                            f"{config.MIN_SIGNALS_TO_PROPOSE_TOPIC} signals before a topic "
                            "leaves candidate status, and multi-source support is what "
                            "deepens the reads that follow."),
        })

    # L2 — how often does the evidence gate actually reject something?
    total = len(claims) + len(ledger.rejections)
    if total:
        rate = len(ledger.rejections) / total * 100
        out.append({
            "id": "L2",
            "statement": (f"The evidence gate has rejected {len(ledger.rejections)} of "
                          f"{total} attempted claims ({rate:.2f}%)."),
            "counts": {"rejected": len(ledger.rejections), "accepted": len(claims),
                       "attempted": total},
            "implication": ("A zero here would be suspicious, not reassuring: it would mean "
                            "the gate never sees a claim without evidence, which is unlikely "
                            "with this many sources."),
        })

    # L3 — library coverage, in the two populations that actually exist.
    # ``topic.claims`` is an accumulator that predates schema-v2 subjects: it
    # kept credits for entity topics whose claim rows never recorded the entity.
    # A lesson that counts only that credit overstates what the ledger can
    # re-prove; one that counts only row-provable support erases real legacy
    # history.  Report both, labelled, and never blend them into one number.
    row_counts = ledger.topics_with_claims()
    row_provable = sum(1 for slug in library.topics if row_counts.get(slug, 0) > 0)
    credit_only = sum(1 for slug, t in library.topics.items()
                      if row_counts.get(slug, 0) == 0 and t.claims > 0)
    tracked = len(library.topics)
    if tracked:
        pct = row_provable / tracked * 100
        extra = (f" {credit_only} more carry only pre-schema-v2 claim credit, which "
                 f"the claim rows can no longer prove; they are disclosed on the "
                 f"Library page, not counted as verified."
                 if credit_only else "")
        out.append({
            "id": "L3",
            "statement": (f"{row_provable} of {tracked} tracked topics ({pct:.1f}%) "
                          f"have at least one accepted claim row that names them."
                          f"{extra}"),
            "counts": {"topicsTracked": tracked, "topicsWithClaimRows": row_provable,
                       "topicsWithCreditOnly": credit_only,
                       "topicsWithNeither": tracked - row_provable - credit_only,
                       "percentRowProvable": round(pct, 2)},
            "implication": ("Anything below 100% is a real coverage gap and is listed as such "
                            "on the site rather than filled with prose. A topic counted "
                            "only by legacy credit is a disclosure, not a verification."),
        })

    # L4 — which idea kinds survive?
    if ideas:
        kinds: Dict[str, List[float]] = {}
        for i in ideas:
            kinds.setdefault(i.kind, []).append(i.robustness)
        rows = sorted(((k, sum(v) / len(v), len(v)) for k, v in kinds.items()),
                      key=lambda x: -x[1])
        if rows:
            best = rows[0]
            out.append({
                "id": "L4",
                "statement": (f"Of {len(rows)} idea kinds, “{best[0]}” holds the highest mean "
                              f"robustness ({best[1]:.3f} over {best[2]} ideas)."),
                "counts": {k: {"meanRobustness": round(m, 4), "n": n} for k, m, n in rows},
                "implication": ("Idea generation spends its budget on the kinds that have "
                                "actually held up, and reports the ones that have not."),
            })

    # L5 — source reliability spread
    rel = memory.get("sourceReliability") or {}
    if rel:
        healthy = [s for s, v in rel.items() if v >= 0.8]
        sick = [s for s, v in rel.items() if v < 0.2]
        out.append({
            "id": "L5",
            "statement": (f"{len(healthy)} of {len(rel)} registered sources are reading "
                          f"reliably (EMA ≥ 0.8); {len(sick)} are effectively unreadable "
                          f"(EMA < 0.2)."),
            "counts": {"sources": len(rel), "healthy": len(healthy), "unreliable": len(sick),
                       "unreliableIds": sorted(sick)},
            "implication": ("A failed response produces no fresh claim. An exact-URL seed, "
                            "if reused, remains explicitly stale; the availability gap stays "
                            "visible on the site."),
        })

    return out


def record_cycle(memory: Dict[str, Any], cycle: int, now: str,
                 summary: Dict[str, Any]) -> Dict[str, Any]:
    memory["cyclesRun"] = cycle
    memory["lastCycleAt"] = now
    if summary.get("ok"):
        memory["consecutiveCycleFailures"] = 0
    else:
        memory["consecutiveCycleFailures"] = int(memory.get("consecutiveCycleFailures", 0)) + 1
    hist = list(memory.get("history") or [])
    hist.append({"cycle": cycle, "at": now,
                 "claims": summary.get("claimsTotal", 0),
                 "topics": summary.get("topicsTotal", 0),
                 "newTopics": summary.get("newTopics", 0),
                 "forecasts": summary.get("forecastsIssued", 0),
                 "scored": summary.get("forecastsScored", 0),
                 "ideas": summary.get("ideas", 0),
                 "irregularities": summary.get("irregularitiesOpen", 0),
                 "readsOk": summary.get("fetchOk", 0),
                 "readsFailed": summary.get("fetchFailed", 0),
                 "errors": len(summary.get("errors") or []),
                 "ok": bool(summary.get("ok"))})
    memory["history"] = hist[-500:]
    return memory
