"""Memory — what the engine remembers between cycles, and how it changes its mind.

Everything here is a number derived from the ledger.  There is no free-text
"belief" store, because a belief that cannot be recomputed cannot be audited.

``data/memory.json`` holds:

* ``strategyWeights``  EMA of each persona's measured skill (drives S06)
* ``sourceReliability`` EMA of each source's probe success rate
* ``topicInterest``    per-topic signal history, which decides promotion/retirement
* ``lessons``          rules the engine has *derived* about its own track record

``lessons`` is the interesting one: it is generated by counting, not by
reflection — e.g. "topics corroborated by ≥2 sources persisted N× longer than
single-source topics" — and each lesson carries the counts that produced it.
"""
from __future__ import annotations

import json
import pathlib
from typing import Any, Dict, List, Optional

from . import config

ALPHA = 0.25


def empty_memory() -> Dict[str, Any]:
    return {
        "cyclesRun": 0,
        "lastCycleAt": "",
        "strategyWeights": {},
        "sourceReliability": {},
        "topicInterest": {},
        "lessons": [],
        "consecutiveCycleFailures": 0,
        "history": [],
    }


def load(data_dir: Optional[pathlib.Path] = None) -> Dict[str, Any]:
    p = pathlib.Path(data_dir or config.DATA) / "memory.json"
    m = empty_memory()
    if not p.exists():
        return m
    try:
        stored = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return m
    if isinstance(stored, dict):
        m.update(stored)
    return m


def save(memory: Dict[str, Any], data_dir: Optional[pathlib.Path] = None) -> None:
    d = pathlib.Path(data_dir or config.DATA)
    d.mkdir(parents=True, exist_ok=True)
    path = d / "memory.json"
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(memory, indent=1, sort_keys=True,
                              allow_nan=False) + "\n", encoding="utf-8")
    tmp.replace(path)


def update_source_reliability(memory: Dict[str, Any], outcomes: Dict[str, bool]) -> Dict[str, Any]:
    """EMA of per-source probe success.  1.0 = always readable, 0.0 = never."""
    rel = dict(memory.get("sourceReliability") or {})
    for sid, ok in outcomes.items():
        prev = rel.get(sid, 0.5)
        rel[sid] = round(prev * (1 - ALPHA) + (1.0 if ok else 0.0) * ALPHA, 6)
    memory["sourceReliability"] = rel
    return memory


def update_topic_interest(memory: Dict[str, Any], signals: Dict[str, int], cycle: int) -> Dict[str, Any]:
    ti = dict(memory.get("topicInterest") or {})
    for slug, n in signals.items():
        cur = ti.get(slug)
        if not isinstance(cur, dict):
            cur = {"ema": 0.0, "seen": 0, "lastCycle": 0, "peak": 0.0}
        cur["ema"] = round(cur["ema"] * (1 - ALPHA) + float(n) * ALPHA, 4)
        cur["seen"] = int(cur.get("seen", 0)) + 1
        cur["lastCycle"] = cycle
        cur["peak"] = max(float(cur.get("peak", 0.0)), cur["ema"])
        ti[slug] = cur
    memory["topicInterest"] = ti
    return memory


def derive_lessons(memory: Dict[str, Any], ledger, library, ideas) -> List[Dict[str, Any]]:
    """Count the engine's own track record and write down what the counts say.

    Each lesson is a statement plus the integers it came from.  A lesson with no
    supporting count is not written.
    """
    out: List[Dict[str, Any]] = []
    claims = ledger.claims
    if not claims:
        return out

    # L1 — does multi-source corroboration predict persistence?
    multi, single = [], []
    per_topic_srcs: Dict[str, set] = {}
    per_topic_signals: Dict[str, int] = {}
    for c in claims:
        per_topic_srcs.setdefault(c.topic, set()).add(c.source_id)
    for t in library.topics.values():
        n = len(per_topic_srcs.get(t.slug, set()))
        if n >= 2:
            multi.append(t.signals)
        elif n == 1:
            single.append(t.signals)
    if multi and single:
        am = sum(multi) / len(multi)
        asg = sum(single) / len(single)
        if asg > 0:
            out.append({
                "id": "L1",
                "statement": (f"Topics backed by two or more independent sources have "
                              f"averaged {am:.2f} signals against {asg:.2f} for "
                              f"single-source topics — a ratio of {am / asg:.2f}×."),
                "counts": {"multiSourceTopics": len(multi), "singleSourceTopics": len(single),
                           "meanSignalsMulti": round(am, 4), "meanSignalsSingle": round(asg, 4)},
                "implication": ("Corroboration is a better promotion signal than raw signal "
                                "count, so the discovery stage requires "
                                f"{config.MIN_SIGNALS_TO_PROPOSE_TOPIC} signals before a topic "
                                "leaves candidate status."),
            })

    # L2 — how often does the evidence gate actually reject something?
    total = len(claims) + len(ledger.rejections)
    if total:
        rate = len(ledger.rejections) / total * 100
        out.append({
            "id": "L2",
            "statement": (f"The evidence gate has rejected {len(ledger.rejections)} of "
                          f"{total} attempted claims ({rate:.2f}%)."),
            "counts": {"rejected": len(ledger.rejections), "accepted": len(claims),
                       "attempted": total},
            "implication": ("A zero here would be suspicious, not reassuring: it would mean "
                            "the gate never sees a claim without evidence, which is unlikely "
                            "with this many sources."),
        })

    # L3 — use the library's persisted claim credits.  ``c.topic`` is the broad
    # family for most facts; discovered entities are represented in ``subjects``
    # only on schema-v2 rows, so counting raw claim topics either includes the
    # non-library ``source-health`` topic or erases legacy entity support.
    supported = sum(1 for t in library.topics.values() if t.claims > 0)
    tracked = len(library.topics)
    if tracked:
        pct = supported / tracked * 100
        out.append({
            "id": "L3",
            "statement": (f"{supported} of {tracked} tracked topics "
                          f"({pct:.1f}%) have at least one accepted claim credit."),
            "counts": {"topicsWithClaims": supported, "topicsTracked": tracked,
                       "percent": round(pct, 2)},
            "implication": ("Anything below 100% is a real coverage gap and is listed as such "
                            "on the site rather than filled with prose."),
        })

    # L4 — which idea kinds survive?
    if ideas:
        kinds: Dict[str, List[float]] = {}
        for i in ideas:
            kinds.setdefault(i.kind, []).append(i.robustness)
        rows = sorted(((k, sum(v) / len(v), len(v)) for k, v in kinds.items()),
                      key=lambda x: -x[1])
        if rows:
            best = rows[0]
            out.append({
                "id": "L4",
                "statement": (f"Of {len(rows)} idea kinds, “{best[0]}” holds the highest mean "
                              f"robustness ({best[1]:.3f} over {best[2]} ideas)."),
                "counts": {k: {"meanRobustness": round(m, 4), "n": n} for k, m, n in rows},
                "implication": ("Idea generation spends its budget on the kinds that have "
                                "actually held up, and reports the ones that have not."),
            })

    # L5 — source reliability spread
    rel = memory.get("sourceReliability") or {}
    if rel:
        healthy = [s for s, v in rel.items() if v >= 0.8]
        sick = [s for s, v in rel.items() if v < 0.2]
        out.append({
            "id": "L5",
            "statement": (f"{len(healthy)} of {len(rel)} registered sources are reading "
                          f"reliably (EMA ≥ 0.8); {len(sick)} are effectively unreadable "
                          f"(EMA < 0.2)."),
            "counts": {"sources": len(rel), "healthy": len(healthy), "unreliable": len(sick),
                       "unreliableIds": sorted(sick)},
            "implication": ("A failed response produces no fresh claim. An exact-URL seed, "
                            "if reused, remains explicitly stale; the availability gap stays "
                            "visible on the site."),
        })

    return out


def record_cycle(memory: Dict[str, Any], cycle: int, now: str,
                 summary: Dict[str, Any]) -> Dict[str, Any]:
    memory["cyclesRun"] = cycle
    memory["lastCycleAt"] = now
    if summary.get("ok"):
        memory["consecutiveCycleFailures"] = 0
    else:
        memory["consecutiveCycleFailures"] = int(memory.get("consecutiveCycleFailures", 0)) + 1
    hist = list(memory.get("history") or [])
    hist.append({"cycle": cycle, "at": now,
                 "claims": summary.get("claimsTotal", 0),
                 "topics": summary.get("topicsTotal", 0),
                 "newTopics": summary.get("newTopics", 0),
                 "forecasts": summary.get("forecastsIssued", 0),
                 "scored": summary.get("forecastsScored", 0),
                 "ideas": summary.get("ideas", 0),
                 "irregularities": summary.get("irregularitiesOpen", 0),
                 "readsOk": summary.get("fetchOk", 0),
                 "readsFailed": summary.get("fetchFailed", 0),
                 "errors": len(summary.get("errors") or []),
                 "ok": bool(summary.get("ok"))})
    memory["history"] = hist[-500:]
    return memory
